services:
  - type: web
    name: enrollment-system
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz.php
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL
        value: "true"
      - key: APP_DEBUG
        value: "true"
      - key: DB_AUTO_INIT
        value: "true"
      - key: SEED_DEMO_DATA
        value: "true"
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "NCST Maritime Academy"
